name: Checks

on:
  workflow_dispatch: ~
  push:
    branches: ['master', '*.x']
  pull_request: ~

jobs:
  run-all-checks-on-php84:
    runs-on: ubuntu-latest
    name: Run all checks on PHP 8.4
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      # Install tools
      - name: Install composer-require-checker
        uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader --working-dir=./tools/composer-require-checker
      - name: Install composer-unused
        uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader --working-dir=./tools/composer-unused
      - name: Install deptrac
        uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader --working-dir=./tools/deptrac
      - name: Install php-cs-fixer
        uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader --working-dir=./tools/php-cs-fixer
      - name: Install psalm
        uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader --working-dir=./tools/psalm
      # Run all checks
      - name: Run all checks
        run: composer run checks

  test-old-php:
    runs-on: ubuntu-latest
    name: Run tests on old PHP version
    strategy:
      matrix:
        php: [ 8.1, 8.2, 8.3 ]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: composer phpunit
