name: Split releases

on:
  release:
    types: ['published']

concurrency:
  group: split

env:
  GH_TOKEN: ${{ secrets.SPLITTER_ACCESS_TOKEN }}

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - { namespace: Message, repo: message }
          - { namespace: MessageBus, repo: message-bus }
          - { namespace: DoctrineORMBridge, repo: doctrine-orm-bridge }
          - { namespace: TrollbusBundle, repo: trollbus-bundle }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: |
          SPLIT_SHA=`git subtree split --prefix=src/${{ matrix.package.namespace }}`
          REPO_URL="https://${{ secrets.SPLITTER_ACCESS_TOKEN }}@github.com/trollbus/${{ matrix.package.repo }}.git"
          gh release create ${{ github.event.release.tag_name }} \
            --verify-tag \
            --repo trollbus/${{ matrix.package.repo }} \
            --target "$SPLIT_SHA" \
            --generate-notes \
            --notes '[Full release information in Trollbus monorepo](https://github.com/trollbus/trollbus/releases/tag/${{ github.event.release.tag_name }}).'
